version: '3.8'
services:

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - db_network
    restart: always

  edugo-app:
    container_name: emod-app
    build: .
    image: anjeonghoo/emod
    environment:
      - SPRING_DATASOURCE_USERNAME=emoddatabase
      - SPRING_DATASOURCE_PASSWORD=emoddatabase
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - redis
    networks:
      - db_network

networks:
  db_network:
    driver: bridge