openai:
  model: gpt-3.5-turbo
  api:
    key: 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
    url: https://api.openai.com/v1/chat/completions
  options:
    temperature: 0.2
    maxTokens: 512